/** Re-export contracts + envelopes for API consumers. */
export type {
  ApiSuccess,
  ApiError,
  ApiErrorBody,
  ApiSuccessMeta,
  AuthSession,
  AuthUser,
  Business,
  Service,
  Professional,
  Client,
  Appointment,
  AvailabilitySlot,
  CancellationPolicy,
  WaitlistEntry,
  PublicStorefront,
  PublicStorefrontView,
  DayCashSummary,
  ReminderTemplate,
  ReminderJob,
  HonorariosQuote,
  HonorariosQuoteRequest,
  TeamInvite,
  AppNotification,
  PushPreference,
  Review,
  GalleryItem,
  Profile,
  Niche,
  UserRole,
  ListQuery,
  AvailabilityQuery,
} from '@/contracts';
